### PR TITLE
feat: add `genObjectFromValues`

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Sometimes it is necessary to generate an object preserving types

```js
// in this case 'bar' is undefined
genObjectFromRaw({ foo: 'bar' }) = '{ foo: bar }';

// in this case 'bar' is a string
genObjectFromValues({ foo: 'bar' }) = '{ foo: "bar" }';
```

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
wdty @danielroe, @pi0 ?

**Comment by pi0** [comment]
Thanks for the PR @ricardogobbosouza. I believe this had to be default behavior preserving types for serialization. /cc @danielroe Any reason why not to make default?

**Comment by ricardogobbosouza** [comment]
@pi0 I didn't put it as default because this is a breaking change

**Comment by ricardogobbosouza** [comment]
Maybe rename to `preservingTypes`

**Comment by ricardogobbosouza** [comment]
It makes more sense to have another function..
I will refactor this PR

**Comment by ricardogobbosouza** [comment]
@pi0, @danielroe 
added `getObjectFromValues`

**Comment by ricardogobbosouza** [comment]
@pi0, @danielroe Any idea when it will be merged?

**Pull request merged**
